#!/bin/bash

declare -a phalena
phalena=($PHALENA)

if [[ $1 == upgrade ]]; then
    if [[ ${PHALENA+@} ]]; then
        if [[ ${phalena[1]} -lt 1 ]]; then
            echo 'PLEASE RESTART PHALENA!'
            echo 'PLEASE RESTART PHALENA!'
            echo 'PLEASE RESTART PHALENA!'
        else
            eval "echo 'finish:reopen' >&${phalena[0]}"
        fi
    fi
fi

exit 0
